platform :ios, '8.0'
#use_frameworks!

target 'CookBook' do
  	pod 'FMDB'
	pod 'JSONModel'
	pod 'SDWebImage'
	pod 'AFNetworking'
	pod 'MGSwipeTableCell'
	pod 'MagicalRecord'
	pod 'SVProgressHUD'
	pod 'GPUImage'
	pod 'AMapLocation'
	pod 'RDVTabBarController'
	pod 'MBProgressHUD'
	pod 'UMengSocial'
	pod 'MJRefresh'
	pod 'MWPhotoBrowser'
end

